# Generated by Django 5.0.4 on 2024-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_post_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "direction",
                    models.CharField(max_length=100, verbose_name="Направление"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "vk_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="VK ID"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="employees/", verbose_name="Фото"),
                ),
            ],
            options={
                "verbose_name": "Работник",
                "verbose_name_plural": "Работники",
            },
        ),
    ]
