# Generated by Django 5.0.4 on 2024-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_employee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Сотрудник", "verbose_name_plural": "Сотрудники"},
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employees/", verbose_name="Фото"
            ),
        ),
    ]
