# Generated by Django 4.1 on 2024-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="quote",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Девиз"
            ),
        ),
    ]
