# Generated by Django 4.1 on 2024-04-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_usermessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermessage",
            options={
                "verbose_name": "Сообщение пользователя",
                "verbose_name_plural": "Сообщения пользователей",
            },
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="date_sent",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="message",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="status",
            field=models.CharField(
                default="pending", max_length=20, verbose_name="Статус"
            ),
        ),
    ]
