# Generated by Django 4.1 on 2024-04-29 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_contactformsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactformsubmission",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done")],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="contactformsubmission",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+999999999'. Допустимая длина от 9 до 15 цифр.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
