# Generated by Django 4.1 on 2024-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_contactformsubmission_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactformsubmission",
            options={
                "verbose_name": "Сообщение пользователя",
                "verbose_name_plural": "Сообщения пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="usermessage",
            options={
                "verbose_name": "Вопрос пользователя",
                "verbose_name_plural": "Вопросы пользователей",
            },
        ),
        migrations.AlterField(
            model_name="contactformsubmission",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Телефон"),
        ),
    ]
