# Generated by Django 4.1 on 2024-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_consultationrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultationrequest",
            name="email",
        ),
        migrations.AlterField(
            model_name="consultationrequest",
            name="preferred_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
