# Generated by Django 4.1 on 2024-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_remove_consultationrequest_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCalculationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("niche", models.CharField(max_length=100)),
                ("functionality", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
