# Generated by Django 4.1 on 2024-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_costcalculationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonetizationQuestionsRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("question", models.TextField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
