# Generated by Django 4.1 on 2024-10-11 13:15

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0020_monetizationquestionsrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="quote",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Quote"
            ),
        ),
    ]
