# Generated by Django 4.1 on 2024-10-16 09:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0021_alter_employee_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcalculationrequest",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
