# Generated by Django 4.1 on 2024-10-16 09:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_alter_costcalculationrequest_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcalculationrequest",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="RU"
            ),
        ),
    ]
