# Generated by Django 4.1 on 2024-09-01 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("resume_file", models.FileField(upload_to="resumes/")),
                ("date_sent", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
        ),
    ]
