# Generated by Django 4.1 on 2024-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="cover_letter",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
